### basic route
GET http://localhost:8080



### add a new employee
POST http://localhost:3000/api/new
content-type: application/json

{
    "first_name" : "adel",
    "last_name" : "khosi",
    "email": "adel@shaper.co.za",
    "contactNo": "0987654321",
    "photo": "image.jpg"
}



### get all employees
GET http://localhost:3000/api/all



### get one employee
GET http://localhost:3000/api/one/1