### basic route
GET http://localhost:8080



### basic route
POST http://localhost:8080/api/new
content-type: application/json

{
    "first_name" : "rori",
    "last_name" : "madisha",
    "email": "rori@shaper.co.za",
    "contactNo": "0987654321"
}