### basic route
GET http://localhost:3000



### admin register route
POST http://localhost:3000/auth/register


### admin login route
POST http://localhost:3000/auth/login
content-type: application/json

{
    "email": "admin@shaper.co.za",
    "password": "admin123"
}


### add a new employee
POST http://localhost:3000/api/new
content-type: application/json

{
    "first_name" : "adel",
    "last_name" : "khosi",
    "email": "adel@shaper.co.za",
    "contactno": "0987654321",
    "emp_role" : 2,
    "start_date": "01/Jan/2023"
}



### get all employees
GET http://localhost:3000/api/all



### get one employee
GET http://localhost:3000/api/one/1




### edit/update employee details
PUT http://localhost:3000/api/edit/2
content-type: application/json

{
    "email": "adel@shaper.co.za",
    "contactno": "0600817701",
    "emp_role" : "3",
    "emp_status": "1"
}


